### ISSUE TITLE
Performance - considerations

### ISSUE THREAD

**Issue by lucasconstantino** [guisouza/dss#11]
Hi, there! First of all, great project.

I have to say I did not spent the time yet to read and learn all the code you have here, but I would like to bring up some discussion about performance - which I imagine will be an important point of interest for anyone considering using your library. First I have some assumptions which might turn out wrong, so here we go:

1 - You modify CSS rules at the stylesheet level, leaving to the browser the task of reproducing the changes to the matching elements;
2 - You have some kind of a templating language to construct this stylesheet;
3 - You parse the expression values with a lexer of some kind.

All these assumptions make clear that you have subsets of quite complex tools to finish the job of dynamic stylesheets. Therefore I would strongly recommend that you consider using tools well know (or at least good enough) for it's particular job, even if this means forking a project to match the needs of DSS on the long-run.

Finally, I've create this topic to aggregate the wide discussion of performance. I think we can split this issue into as many issues as necessary to discuss the more specificity of each aspect that gets pointed here.

**Comment by guisouza** [comment]
- 1 :+1: yeap, and its a good strategy, its faster than inline style all the matching elements
- 2 :+1: yeap ..  that syntax (#12)
- 3 :+1: yeap .. regExp 

First of all I want to focus in minor problems like, only fire Mouse,Scroll,windowResize events when these dynamic properties is being used. There is a lot of minor fixes like this in the refresh lifecycle.  

and than, I would like to improve the parsing strategy with an handmade Lexer ..

**Comment by lucasconstantino** [comment]
I'll have a look at the architecture later so that I don't write about topics which you have already covered in code, but for now: 

**About the events**, though, I would suggest using a true evented API so that people can indeed trigger the rendering manually, allowing for really dynamic stuff and leaving performance issues such as run cycle (timeout loops or whatever) to the implementation that triggers stuff. For instance, I don't this the `addDefaultProperty` is a nice approach; you are limiting extensions to a predefined configuration based pattern, while I think you should leave it to the extensions or plugins. Mouse events, scrolling, or timebased changes should therefore be encapsulated in self-contained extensions, meaning we don't need their performance hit unless these extensions get initialized. Of course you can keep them in core; but we should have a mean to disable them when necessary - or even have them disabled by default. Thus, this kind of architecture would diminish the need for your code to be smart enough and set listeners when properties are indeed used in the stylesheet, avoiding even the need of a core-based lifecycle.

**Lexer**: a complex topic. We should definitely try and get the help of an expert on the matter.

Ps.: I realize I'm being very intrusive in proposing architecture changes, but please take them all as suggestions and even some as pure rambling.

**Comment by guisouza** [comment]
**_about the events**_ 
addDefaultProperty is just sugar-syntax to something like : 

``` javascript
document.addEventListener('mousemove',function(event){
    dss.setProperty('mouseX',event.pageX)
    dss.setProperty('mouseY',event.pageY)
})
```

**Comment by guisouza** [comment]
I know ..  its more like salt-syntax   husahuAUHHUaSHUHUASHUAHUaHUA

**Comment by lucasconstantino** [comment]
Hahahaha

Yeah, that part of the event listener setup I had already seen. That's exactly what I think should be distributed to other people's code. For sure you can have some in core, but to define that a property MUST listen to a given context' event sound very limiting. That's for sure not part of your core product here.

**Comment by guisouza** [comment]
yeah, BUUUUT ..  my core should take care of the hard decision "Should I listen ?" . 
So ..  i am considering start to listen/firing the event, only when that Namespace is being used ...

**Comment by leocavalcante** [comment]
I think you should let dynamic properties be handled by the consumer instead of manage it in this declarative way. People already know how to deal with events, you can keep this concern out of DSS and focus the library in make dynamic CSS changes with high performance.

As you stated:

``` js
document.addEventListener('mousemove',function(event){
    dss.setProperty('mouseX',event.pageX)
    dss.setProperty('mouseY',event.pageY)
})
```

Is better than:

``` js
dss.setDynamicProperty('mouse',function(){
    return{
        context : document,
        event : 'mousemove',
        getter : function(e){
            return {
                x : e.pageX,
                y : e.pageY,
            };
        }
    };
});
```

Plus: what about using CSS as a config file that parses once and maps to styles DOM properties instead on repeating the cycle (generate/render..) for each setProperty?

``` js
dss.setProperty('mouseX',event.pageX)
dss.setProperty('mouseY',event.pageY)
```

This will recycle twice?

**Comment by guisouza** [comment]
@leocavalcante, 

``` javascript
dss.setProperty('mouseY',event.pageY)
```

where did event.pageX came from in your last declaration suggestion?

**Comment by guisouza** [comment]
Many performance issues were solved with 0ef133f064e163f18b7bfc528e0e59b107cd31c6

We still need to listen only the needed events #20..
it will be closed for a while

**Comment by guisouza** [comment]
thanks for your time and attention :heart:

**Comment by leocavalcante** [comment]
Hi @guisouza, nice to see the project getting fuel to the fire again.

My question was about `dss.setProperty` be called twice just a line after other. It will make the whole cycle again, didn't it? For each call...

Having something like 'dss.setProperties({mouseX: pageX, mouseY: pageY})' could save some memory. What you think?

**Comment by gabrieljmj** [comment]
@leocavalcante and it is more beautiful for more than one property

**Comment by guisouza** [comment]
@leocavalcante 2cc56f76657f7d6f588642e741d496ec250a2f08 its there ! =D 

:heart: :octocat:
