### ISSUE TITLE
AST to get rules

### ISSUE THREAD

**Issue by mauriciosoares** [guisouza/dss#15]
Hey Gui! you really are a programming magician, nice project!

I have a suggestion for you, to make your project a lot easier to implement new features and stuff, you may use AST for parsing the CSS rules.

Saying is easier than doing, so I have implemented a simple dss-ast project with a working example... you may check it out! You (or we) could refactor the code if you consider using AST for your project

https://github.com/mauriciosoares/dss-ast

![so_good](https://cloud.githubusercontent.com/assets/2321259/10117874/e2e650f4-643c-11e5-9e3b-13405a3ffd65.png)

**Comment by leocavalcante** [comment]
Really nice :+1: 
That's what I'm talking about at #11

**Comment by zenorocha** [comment]
+1 for AST

**Comment by guisouza** [comment]
af1a0493f27c564773dc81ab851852537bb91afd =D
