### ISSUE TITLE
remove all default auto-binding properties.

### ISSUE THREAD

**Issue by mauriciosoares** [guisouza/dss#16]
Hey man, what you think about removing all the auto-binding properties, and let the user to set them up by himself?

Because Imagine I want to use DSS only with a custom property I've created, but still I have 3 heavy events in the DOM  that I'll never use, the `mousemove`, `scroll` and `resize`. These are going to be triggered a LOT, and I'm not even using them.

Just a thought.

**Comment by guisouza** [comment]
You are absolutely right!

The setDynamicProperty method will only start to fire events when its nameSpace is being used in the DSS sheet ..  
Thats why I created this kind of "salty syntax" : 

``` javascript
dss.setDynamicProperty('mouse',function(){
    return{
        context : document,

        event : 'mousemove',

        getter : function(e){
            return {
                x : e.pageX,
                y : e.pageY,
            };
        }
    };
});
```

instead of it : 

``` javascript
document.addEventListener('mousemove',function(e){
    dss.setProperty('mouseX',e.pageX);
    dss.setProperty('mouseY',e.pageY);
})

```

I will implement it ..   I promise . .

**Comment by mauriciosoares** [comment]
Cool!

I'll close this issue for now, as you'll improve them instead of remove.

**Comment by guisouza** [comment]
tks for your time and attention <3 !
