### ISSUE TITLE
onParsed listener?

### ISSUE THREAD

**Issue by gabrielbiga** [guisouza/dss#19]
Is there any listener to be triggered if the CSS finished the parsing process?

**Comment by guisouza** [comment]
every "onReady" API aims to tell the developer that something is ready to use .. 
But as the DSS API is always available to use since it is included, I didn't implemented an event like that.
Could you show me a use case for it?

**Comment by gabrielbiga** [comment]
Is for prevent the user see the page mounting.
I already have a loading spinner for that. I just need to know when the DSS ends the process (Ajax Request of the CSS + Parsing) to hide the loading spinner.

I use the event "DOMSubtreeModified" to check if the "dss-generated-stylesheet" was created, but I think this is a ugly solution...

Do you have some idea for this?

**Comment by guisouza** [comment]
@gabrielbiga 
193dddf0bb4e3977582ff1bc988015a2e0b48570 
Now we have an pub/sub based events engine =D 
We came with 2 events out of the box and here it is :  

### init

``` javascript
dss.on('init',function(){
console.log('DSS initialized with its first render Cycle =D ')
})
```

### render

``` javascript
dss.on('render',function(){
console.log('there is a render cycle =D')
})
```

Thanks for your time and attention ! :heart: :heart: :heart:

issue closed for a while =D

**Comment by gabrielbiga** [comment]
YEAAAH! tks @guisouza! :+1:
