### ISSUE TITLE
[SPIKE] Use PostCSS to process CSS

### ISSUE THREAD

**Issue by fernandofleury** [guisouza/dss#24]

**Comment by guisouza** [comment]
+1 +1 +1 +1  Im on it! =]

**Comment by fernandofleury** [comment]
postcss works out of the box on browser:

``` js
import postcss from 'postcss';

let result = postcss.rule({
  selector: '.result'
})
.append({
  prop: 'background-color',
  value: 'black'
});

let stylesheet = postcss.root().append(result);

console.log(stylesheet.toResult());
```

![image](https://cloud.githubusercontent.com/assets/2780941/12643940/814de7e6-c5a6-11e5-8695-fae3c1de1b38.png)

I guess now the point is how dss can take advantage of it, taking the heavy work out of it and putting directly to postcss.

**Comment by fernandofleury** [comment]
common plugin usage works as well:

``` js
import postcss from 'postcss';
import autoprefixer from 'autoprefixer';

let result = postcss.rule({
  selector: '.result'
})
.append({
  prop: 'display',
  value: 'flex'
});

let stylesheet = postcss.root().append(result);

let processed = postcss([autoprefixer]).process(stylesheet);
```

``` css
.result {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

![image](https://cloud.githubusercontent.com/assets/2780941/12644295/0ba0798e-c5a9-11e5-8e09-37f5f425d3b4.png)

sure there will be a couple of plugins which won't work cause of direct deps of low level modules not ported to the browser (One I can think of is font-magician, which directly relies on fs to perform few operations), but that sure is expendable.

**Comment by fernandofleury** [comment]
We can rely on atRules to communicate with postcss, something like `value: @dss-mouseY`. But it could be expanded to `@dss` then the directive to be used `@dss mouseY`. Lots of options here.

**Comment by fernandofleury** [comment]
Reading the core of the project atm. I've got a couple of ideas how to make this work out.

**Comment by guisouza** [comment]
;(
