### ISSUE TITLE
Mouse position property returning boolean

### ISSUE THREAD

**Issue by rafael-telles** [guisouza/dss#5]
Hi!

When I hit the left or top edges of the page, `mouseX` and `mouseY` return `false`.

**Comment by guisouza** [comment]
https://github.com/guisouza/dss/commit/6a795af6dff3faf1542696ed59134537654d924d
I think it is the root of the problem ..

**Comment by rafael-telles** [comment]
Sorry, I thought it was a problem with `pageX` and `pageY` properties. xD
Thanks!
